#
# (C) Copyright 2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y += jz_sfc_common.o

ifdef CONFIG_MTD_SFCNOR
obj-y += jz_sfc_nor.o
obj-y += jz_sfc_ops.o
endif
