/*
 * DO NOT MODIFY.
 *
 * This file was generated by sfc_timing_params
 *
 */

#ifndef __SFC_TIMING_VAL_H__
#define __SFC_TIMING_VAL_H__

#define DEF_TIM_VAL 0x000100e7

#endif /* __SFC_TIMING_VAL_H__ */
