/* Warnning: Please set ddr driver strength.*/

/*
 * DO NOT MODIFY.
 *
 * This file was generated by ddr_params_creator
 *
 */

#ifndef __DDR_REG_VALUES_H__
#define __DDR_REG_VALUES_H__

#define DDRC_CFG_VALUE			0x2a002a29
#define DDRC_CTRL_VALUE			0x0000b092
#define DDRC_DLMR_VALUE			0x00000006
#define DDRC_DDLP_VALUE			0x00000000
#define DDRC_MMAP0_VALUE		0x000020f8
#define DDRC_MMAP1_VALUE		0x00002800
#define DDRC_REFCNT_VALUE		0x40b60083
#define DDRC_TIMING1_VALUE		0x06110c06
#define DDRC_TIMING2_VALUE		0x0a10060c
#define DDRC_TIMING3_VALUE		0x030e0410
#define DDRC_TIMING4_VALUE		0x26302008
#define DDRC_TIMING5_VALUE		0x1b0c0066
#define DDRC_AUTOSR_CNT_VALUE		0x31000101
#define DDRC_AUTOSR_EN_VALUE		0x00000001
#define DDRC_HREGPRO_VALUE		0x00000001
#define DDRC_PREGPRO_VALUE		0x00000001
#define DDRC_CGUC0_VALUE		0x11111111
#define DDRC_CGUC1_VALUE		0x00000113
#define DDRP_MEMCFG_VALUE		0x00000012
#define DDRP_CL_VALUE			0x0000000c
#define DDRP_CWL_VALUE			0x00000006
#define	DDR_MR0_VALUE			0x00000000
#define	DDR_MR1_VALUE			0x00000143
#define	DDR_MR2_VALUE			0x0000021a
#define	DDR_MR3_VALUE			0x00000302
#define	DDR_MR10_VALUE			0x00000aab
#define	DDR_MR11_VALUE			0x00000b02
#define	DDR_MR63_VALUE			0x00003ffc
#define	DDR_CHIP_0_SIZE			134217728
#define	DDR_CHIP_1_SIZE			0
#define REMMAP_ARRAY {\
	0x030e0d0c,\
	0x07060504,\
	0x0b0a0908,\
	0x0f020100,\
	0x13121110,\
}
#define timing1_tWL		6
#define timing1_tWR		12
#define timing1_tWTR		17
#define timing1_tWDLAT		6
#define timing2_tRL		12
#define timing2_tRTP		6
#define timing2_tRTW		16
#define timing2_tRDLAT		10
#define timing3_tRP		16
#define timing3_tCCD		4
#define timing3_tRCD		14
#define timing3_ttEXTRW		3
#define timing4_tRRD		8
#define timing4_tRAS		32
#define timing4_tRC		48
#define timing4_tFAW		38
#define timing5_tCKE		6
#define timing5_tXP		6
#define timing5_tCKSRE		0
#define timing5_tCKESR		12
#define timing5_tXS		27

#endif /* __DDR_REG_VALUES_H__ */
