#
# Ingenic JZ4780 makefile
#
# Copyright (c) 2013 Imagination Technologies
# Author: Paul Burton <paul.burton@imgtec.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-y	= $(SOC).o
obj-y	+= pll.o
obj-y	+= sdram.o
obj-y	+= timer.o
