#
# Copyright (c) 2009 Wind River Systems, Inc.
# Tom Rix <Tom.Rix at windriver.com>
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_PMU_ACT8600) += act8600.o
obj-$(CONFIG_PMU_RICOH6x) += ricoh619-regulator.o
obj-$(CONFIG_PMU_SM5007) += sm5007-regulator.o
obj-$(CONFIG_PMU_EA3056) += ea3056-regulator.o
